version: "3.9"  # optional since v1.27.0
services:
  fluentd:
    container_name: fluentd
    image: fluentd:latest
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - .:/fluentd/etc
