version: "3.9"  # optional since v1.27.0
services:
  elasticsearch:
    container_name: elasticsearch
    image: "docker.elastic.co/elasticsearch/elasticsearch:${ES_TAG}"
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
  fluentd:
    container_name: fluentd
    image: fluentd:latest
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - .:/fluentd/etc
