version: "3"  # optional since v1.27.0
services:
  elasticsearch:
    container_name: elasticsearch
    image: "docker.elastic.co/elasticsearch/elasticsearch:${ES_TAG}"
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    healthcheck:
      test: curl -X GET "localhost:9200/_cluster/health?wait_for_status=yellow&timeout=50s&pretty" || exit 1

  fluentd:
    build: ./fluentd
    container_name: fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      - "24220:24220"
    volumes:
      - ./fluentd/config:/fluentd/etc
    healthcheck:
      test: curl "http://localhost:24220/api/plugins.json"
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.10.1
    ports:
      - "5601:5601"
    container_name: kibana
    healthcheck:
      test: curl "http://localhost:5601/status"
    depends_on:
      - elasticsearch

  log-generator:
    container_name: python-log-generator
    build: ./python
    depends_on:
      - fluentd
